POLYGON_API_KEY = "jT5zs9Lg8zeqP1qUlohAydN8xiLujKZn"
TIINGO_API_KEY = ""
ALPACA_KEY_ID = "PKZ34BJQ1DGFE9JM5NPV"
ALPACA_SECRET_KEY = "x1BWPJ1yTddpoOVZrLJESvNmnfuvRO4kvqnHTDYG"

DATA_DIR = "data/minute_bars"
REPORTS_DIR = "reports"

DEFAULT_SYMBOLS = ["AAPL", "MSFT", "NVDA", "AMD", "TSLA"]
